CREATE TABLE `bf_reports` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `dt_created` DATETIME NOT NULL DEFAULT 0,
  `executiontime` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  `parameters` TEXT NOT NULL DEFAULT '',
  `filecount` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  `active` INTEGER UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY(`id`)
);

CREATE TABLE `bf_report_results` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `report_id` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  `type` VARCHAR(45) NOT NULL DEFAULT '',
  `rule` VARCHAR(255) NOT NULL DEFAULT '',
  `rulefile` VARCHAR(255) NOT NULL DEFAULT '',
  `rulename` VARCHAR(255) NOT NULL DEFAULT '',
  `file` VARCHAR(255) NOT NULL DEFAULT '',
  `line` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  `position` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  `message` TEXT NOT NULL DEFAULT '',
  `code` TEXT NOT NULL DEFAULT '',
  PRIMARY KEY(`id`)
);

CREATE TABLE `bf_profiles` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `dt_created` DATETIME NOT NULL DEFAULT 0,
  `parameters` TEXT NOT NULL DEFAULT '',
  `active` INTEGER UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY(`id`)
);